# Generated by Django 5.2.4 on 2025-08-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contributor_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['project__name', 'role']},
        ),
    ]
