# Generated by Django 5.2.4 on 2025-08-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_time']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_time']},
        ),
    ]
